name: POC Workflow
on:
  [push]
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Hellow World
        run: |
          echo "Hello World!"
